// This file was generated by the "yardl" tool. DO NOT EDIT.

#pragma once
#include <array>
#include <complex>
#include <memory>
#include <optional>
#include <variant>
#include <vector>

#include "../yardl/detail/ndjson/reader_writer.h"
#include "../protocols.h"
#include "../types.h"

namespace evo_test::ndjson {
// NDJSON writer for the MyProtocol protocol.
class MyProtocolWriter : public evo_test::MyProtocolWriterBase, yardl::ndjson::NDJsonWriter {
  public:
  MyProtocolWriter(std::ostream& stream)
      : yardl::ndjson::NDJsonWriter(stream, schema_) {
  }

  MyProtocolWriter(std::string file_name)
      : yardl::ndjson::NDJsonWriter(file_name, schema_) {
  }

  void Flush() override;

  protected:
  void WriteHeaderImpl(evo_test::Header const& value) override;
  void WriteIdImpl(int64_t const& value) override;
  void WriteSamplesImpl(evo_test::Sample const& value) override;
  void EndSamplesImpl() override {}
  void WriteMaybeImpl(std::optional<int32_t> const& value) override;
  void WriteFooterImpl(std::optional<evo_test::Footer> const& value) override;
  void CloseImpl() override;
};

// NDJSON reader for the MyProtocol protocol.
class MyProtocolReader : public evo_test::MyProtocolReaderBase, yardl::ndjson::NDJsonReader {
  public:
  MyProtocolReader(std::istream& stream)
      : yardl::ndjson::NDJsonReader(stream, schema_) {
  }

  MyProtocolReader(std::string file_name)
      : yardl::ndjson::NDJsonReader(file_name, schema_) {
  }

  protected:
  void ReadHeaderImpl(evo_test::Header& value) override;
  void ReadIdImpl(int64_t& value) override;
  bool ReadSamplesImpl(evo_test::Sample& value) override;
  void ReadMaybeImpl(std::optional<int32_t>& value) override;
  void ReadFooterImpl(std::optional<evo_test::Footer>& value) override;
  void CloseImpl() override;
};

// NDJSON writer for the UnusedProtocol protocol.
class UnusedProtocolWriter : public evo_test::UnusedProtocolWriterBase, yardl::ndjson::NDJsonWriter {
  public:
  UnusedProtocolWriter(std::ostream& stream)
      : yardl::ndjson::NDJsonWriter(stream, schema_) {
  }

  UnusedProtocolWriter(std::string file_name)
      : yardl::ndjson::NDJsonWriter(file_name, schema_) {
  }

  void Flush() override;

  protected:
  void WriteSamplesImpl(evo_test::Sample const& value) override;
  void EndSamplesImpl() override {}
  void CloseImpl() override;
};

// NDJSON reader for the UnusedProtocol protocol.
class UnusedProtocolReader : public evo_test::UnusedProtocolReaderBase, yardl::ndjson::NDJsonReader {
  public:
  UnusedProtocolReader(std::istream& stream)
      : yardl::ndjson::NDJsonReader(stream, schema_) {
  }

  UnusedProtocolReader(std::string file_name)
      : yardl::ndjson::NDJsonReader(file_name, schema_) {
  }

  protected:
  bool ReadSamplesImpl(evo_test::Sample& value) override;
  void CloseImpl() override;
};

} // namespace evo_test::ndjson
