version: 2
updates:
  - package-ecosystem: gomod
    directory: /tooling
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
