# This is an internal pipeline where steps are injected automatically

trigger:
  - main

schedules:
  - cron: "0 0 * * 3"
    displayName: At 00:00 on Wednesdays
    branches:
      include:
        - main
    always: "true"

pr:
  - main

steps: []
