name: yardl
channels:
  - conda-forge
  - defaults
dependencies:
  - bash-completion=2.11 # local
  - ccache=4.11.3 # local
  - clang-format=21.1.2 # local
  - cmake=4.1.2
  - fmt=11.2.0
  - gcc_linux-64=15.1.0 # arch=x86_64
  - gcc_linux-aarch64=15.1.0 # arch=aarch64
  - gdb=16.3 # local
  - gmock=1.17.0
  - gtest=1.17.0
  - gxx_linux-64=15.1.0 # arch=x86_64
  - gxx_linux-aarch64=15.1.0 # arch=aarch64
  - hdf5=1.14.6
  - howardhinnant_date=3.0.4
  - ipykernel=6.30.1 # local
  - just=1.43.0
  - ninja=1.13.1
  - nlohmann_json=3.12.0
  - nodejs=24.9.0 # local
  - numpy=2.3.3
  - pyright=1.1.406
  - pytest=8.4.2
  - python=3.13.7
  - rich=14.1.0
  - shellcheck=0.10.0 # local
  - valgrind=3.25.1 # local arch=x86_64
  - xtensor=0.25.0 # local
