name: yardl
channels:
  - conda-forge
  - defaults
dependencies:
  - bash-completion=2.11 # local
  - ccache=4.5.1 # local
  - clang-format=14.0.4 # local
  - cmake=3.21.3
  - fmt=8.1.1
  - gcc_linux-64=11.2.0 # arch=amd64
  - gcc_linux-aarch64=11.2.0 # arch=aarch64
  - gdb=11.2 # local
  - gmock=1.11.0
  - gtest=1.11.0
  - gxx_linux-64=11.2.0 # arch=amd64
  - gxx_linux-aarch64=11.2.0 # arch=aarch64
  - hdf5=1.12.1
  - howardhinnant_date=3.0.1
  - ipykernel=6.19.2 # local
  - just=1.5.0
  - ninja=1.11.0
  - nlohmann_json=3.11.2
  - nodejs=20.5.1 # local
  - numpy=1.24.3
  - pytest=7.3.2
  - python=3.11.3
  - rich=13.5.1
  - shellcheck=0.8.0 # local
  - xtensor=0.24.2
