name: Configure Environment
description: Configures the conda environment
runs:
  using: composite
  steps:

    - name: Initial setup
      shell: bash
      run: |
        # filter conda environment file
        awk -v arch="$(uname -m)" '
        !/#.*arch=/ && !/#.*\<local\>/ { print; next }
        /#.*arch=/ && $0 ~ "arch="arch { print }
        ' environment.yml > ci-environment.yml

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        # Do not specify environment file - see Cache step below
        activate-environment: yardl
        use-mamba: true

    - name: Get Date
      id: get-date
      shell: bash
      run: echo "DATE=$(date -u +'%Y%m%d')" >> $GITHUB_ENV

    - name: Cache Conda Env
      id: cache-conda
      uses: actions/cache@v2
      with:
        path: ${{ env.CONDA }}/envs
        key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            hashFiles('ci-environment.yml') }}-${{
            env.DATE }}-${{
            env.CONDA_CACHE_NUMBER }}

    - name: Update Environment
      shell: bash
      run: mamba env update -n yardl -f ci-environment.yml
      if: steps.cache-conda.outputs.cache-hit != 'true'


    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
        cache-dependency-path: tooling/go.sum
