name: Configure Environment
description: Configures the conda environment
runs:
  using: composite
  steps:

    - name: Initial setup
      shell: bash
      run: |
        # filter conda environment file
        cat environment.yml | grep -v "#.*\<\local\>" > ci-environment.yml

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: yardl
        environment-file: ci-environment.yml

    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.2'
