name: Configure Environment
description: Configures the conda environment
runs:
  using: composite
  steps:
    - name: Initial setup
      shell: bash
      run: |
        # filter conda environment file
        awk -v arch="$(uname -m)" '
        !/#.*arch=/ && !/#.*\<local\>/ { print; next }
        /#.*arch=/ && $0 ~ "arch="arch { print }
        ' environment.yml > ci-environment.yml

    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "1.5.2"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: yardl
        environment-file: ci-environment.yml

    - uses: actions/setup-go@v4
      with:
        go-version: "1.21.3"
