% This file was generated by the "yardl" tool. DO NOT EDIT.

classdef LinkedList < handle
  properties
    value
    next
  end

  methods
    function self = LinkedList(kwargs)
      arguments
        kwargs.value;
        kwargs.next = yardl.None;
      end
      if ~isfield(kwargs, "value")
        throw(yardl.TypeError("Missing required keyword argument 'value'"))
      end
      self.value = kwargs.value;
      self.next = kwargs.next;
    end

    function res = eq(self, other)
      res = ...
        isa(other, "sketch.LinkedList") && ...
        isequal(self.value, other.value) && ...
        isequal(self.next, other.next);
    end

    function res = ne(self, other)
      res = ~self.eq(other);
    end
  end

end
