// This file was generated by the "yardl" tool. DO NOT EDIT.

#pragma once
#include "types.h"

namespace evo_test {
enum class Version {
  v0,
  Latest
};
// Abstract writer for the ProtocolWithChanges protocol.
class ProtocolWithChangesWriterBase {
  public:
  // Ordinal 0.
  void WriteInt8ToInt(int32_t const& value);

  // Ordinal 1.
  void WriteInt8ToLong(int64_t const& value);

  // Ordinal 2.
  void WriteInt8ToUint(uint32_t const& value);

  // Ordinal 3.
  void WriteInt8ToUlong(uint64_t const& value);

  // Ordinal 4.
  void WriteInt8ToFloat(float const& value);

  // Ordinal 5.
  void WriteInt8ToDouble(double const& value);

  // Ordinal 6.
  void WriteIntToUint(uint32_t const& value);

  // Ordinal 7.
  void WriteIntToLong(int64_t const& value);

  // Ordinal 8.
  void WriteIntToFloat(float const& value);

  // Ordinal 9.
  void WriteIntToDouble(double const& value);

  // Ordinal 10.
  void WriteUintToUlong(uint64_t const& value);

  // Ordinal 11.
  void WriteUintToFloat(float const& value);

  // Ordinal 12.
  void WriteUintToDouble(double const& value);

  // Ordinal 13.
  void WriteFloatToDouble(double const& value);

  // Ordinal 14.
  void WriteIntToString(std::string const& value);

  // Ordinal 15.
  void WriteUintToString(std::string const& value);

  // Ordinal 16.
  void WriteLongToString(std::string const& value);

  // Ordinal 17.
  void WriteUlongToString(std::string const& value);

  // Ordinal 18.
  void WriteFloatToString(std::string const& value);

  // Ordinal 19.
  void WriteDoubleToString(std::string const& value);

  // Ordinal 20.
  void WriteIntToOptional(std::optional<int32_t> const& value);

  // Ordinal 21.
  void WriteFloatToOptional(std::optional<float> const& value);

  // Ordinal 22.
  void WriteStringToOptional(std::optional<std::string> const& value);

  // Ordinal 23.
  void WriteIntToUnion(std::variant<int32_t, bool> const& value);

  // Ordinal 24.
  void WriteFloatToUnion(std::variant<float, bool> const& value);

  // Ordinal 25.
  void WriteStringToUnion(std::variant<std::string, bool> const& value);

  // Ordinal 26.
  void WriteOptionalIntToFloat(std::optional<float> const& value);

  // Ordinal 27.
  void WriteOptionalFloatToString(std::optional<std::string> const& value);

  // Ordinal 28.
  void WriteAliasedLongToString(evo_test::AliasedLongToString const& value);

  // Ordinal 29.
  void WriteStringToAliasedString(evo_test::AliasedString const& value);

  // Ordinal 30.
  void WriteStringToAliasedInt(evo_test::AliasedInt const& value);

  // Ordinal 31.
  void WriteOptionalIntToUnion(std::variant<std::monostate, int32_t, std::string> const& value);

  // Ordinal 32.
  void WriteOptionalRecordToUnion(std::variant<std::monostate, evo_test::RecordWithChanges, std::string> const& value);

  // Ordinal 33.
  void WriteRecordWithChanges(evo_test::RecordWithChanges const& value);

  // Ordinal 34.
  void WriteAliasedRecordWithChanges(evo_test::AliasedRecordWithChanges const& value);

  // Ordinal 35.
  void WriteRecordToRenamedRecord(evo_test::RenamedRecord const& value);

  // Ordinal 36.
  void WriteRecordToAliasedRecord(evo_test::AliasedRecordWithChanges const& value);

  // Ordinal 37.
  void WriteRecordToAliasedAlias(evo_test::AliasOfAliasedRecordWithChanges const& value);

  // Ordinal 38.
  void WriteOptionalRecordWithChanges(std::optional<evo_test::RecordWithChanges> const& value);

  // Ordinal 39.
  void WriteAliasedOptionalRecordWithChanges(std::optional<evo_test::AliasedRecordWithChanges> const& value);

  // Ordinal 40.
  void WriteUnionRecordWithChanges(std::variant<evo_test::RecordWithChanges, int32_t> const& value);

  // Ordinal 41.
  void WriteUnionWithSameTypeset(std::variant<float, evo_test::RecordWithChanges, std::string, int32_t> const& value);

  // Ordinal 42.
  void WriteUnionWithTypesAdded(std::variant<evo_test::RecordWithChanges, int32_t, float, std::string> const& value);

  // Ordinal 43.
  void WriteUnionWithTypesRemoved(std::variant<evo_test::RecordWithChanges, std::string> const& value);

  // Ordinal 44.
  void WriteRecordToOptional(std::optional<evo_test::RecordWithChanges> const& value);

  // Ordinal 45.
  void WriteRecordToAliasedOptional(evo_test::AliasedOptionalRecord const& value);

  // Ordinal 46.
  void WriteRecordToUnion(std::variant<evo_test::RecordWithChanges, std::string> const& value);

  // Ordinal 47.
  void WriteRecordToAliasedUnion(evo_test::AliasedRecordOrString const& value);

  // Ordinal 48.
  void WriteVectorRecordWithChanges(std::vector<evo_test::RecordWithChanges> const& value);

  // Ordinal 49.
  // Call this method for each element of the `streamedRecordWithChanges` stream, then call `EndStreamedRecordWithChanges() when done.`
  void WriteStreamedRecordWithChanges(evo_test::RecordWithChanges const& value);

  // Ordinal 49.
  // Call this method to write many values to the `streamedRecordWithChanges` stream, then call `EndStreamedRecordWithChanges()` when done.
  void WriteStreamedRecordWithChanges(std::vector<evo_test::RecordWithChanges> const& values);

  // Marks the end of the `streamedRecordWithChanges` stream.
  void EndStreamedRecordWithChanges();

  // Optionaly close this writer before destructing. Validates that all steps were completed.
  void Close();

  virtual ~ProtocolWithChangesWriterBase() = default;

  // Flushes all buffered data.
  virtual void Flush() {}

  protected:
  virtual void WriteInt8ToIntImpl(int32_t const& value) = 0;
  virtual void WriteInt8ToLongImpl(int64_t const& value) = 0;
  virtual void WriteInt8ToUintImpl(uint32_t const& value) = 0;
  virtual void WriteInt8ToUlongImpl(uint64_t const& value) = 0;
  virtual void WriteInt8ToFloatImpl(float const& value) = 0;
  virtual void WriteInt8ToDoubleImpl(double const& value) = 0;
  virtual void WriteIntToUintImpl(uint32_t const& value) = 0;
  virtual void WriteIntToLongImpl(int64_t const& value) = 0;
  virtual void WriteIntToFloatImpl(float const& value) = 0;
  virtual void WriteIntToDoubleImpl(double const& value) = 0;
  virtual void WriteUintToUlongImpl(uint64_t const& value) = 0;
  virtual void WriteUintToFloatImpl(float const& value) = 0;
  virtual void WriteUintToDoubleImpl(double const& value) = 0;
  virtual void WriteFloatToDoubleImpl(double const& value) = 0;
  virtual void WriteIntToStringImpl(std::string const& value) = 0;
  virtual void WriteUintToStringImpl(std::string const& value) = 0;
  virtual void WriteLongToStringImpl(std::string const& value) = 0;
  virtual void WriteUlongToStringImpl(std::string const& value) = 0;
  virtual void WriteFloatToStringImpl(std::string const& value) = 0;
  virtual void WriteDoubleToStringImpl(std::string const& value) = 0;
  virtual void WriteIntToOptionalImpl(std::optional<int32_t> const& value) = 0;
  virtual void WriteFloatToOptionalImpl(std::optional<float> const& value) = 0;
  virtual void WriteStringToOptionalImpl(std::optional<std::string> const& value) = 0;
  virtual void WriteIntToUnionImpl(std::variant<int32_t, bool> const& value) = 0;
  virtual void WriteFloatToUnionImpl(std::variant<float, bool> const& value) = 0;
  virtual void WriteStringToUnionImpl(std::variant<std::string, bool> const& value) = 0;
  virtual void WriteOptionalIntToFloatImpl(std::optional<float> const& value) = 0;
  virtual void WriteOptionalFloatToStringImpl(std::optional<std::string> const& value) = 0;
  virtual void WriteAliasedLongToStringImpl(evo_test::AliasedLongToString const& value) = 0;
  virtual void WriteStringToAliasedStringImpl(evo_test::AliasedString const& value) = 0;
  virtual void WriteStringToAliasedIntImpl(evo_test::AliasedInt const& value) = 0;
  virtual void WriteOptionalIntToUnionImpl(std::variant<std::monostate, int32_t, std::string> const& value) = 0;
  virtual void WriteOptionalRecordToUnionImpl(std::variant<std::monostate, evo_test::RecordWithChanges, std::string> const& value) = 0;
  virtual void WriteRecordWithChangesImpl(evo_test::RecordWithChanges const& value) = 0;
  virtual void WriteAliasedRecordWithChangesImpl(evo_test::AliasedRecordWithChanges const& value) = 0;
  virtual void WriteRecordToRenamedRecordImpl(evo_test::RenamedRecord const& value) = 0;
  virtual void WriteRecordToAliasedRecordImpl(evo_test::AliasedRecordWithChanges const& value) = 0;
  virtual void WriteRecordToAliasedAliasImpl(evo_test::AliasOfAliasedRecordWithChanges const& value) = 0;
  virtual void WriteOptionalRecordWithChangesImpl(std::optional<evo_test::RecordWithChanges> const& value) = 0;
  virtual void WriteAliasedOptionalRecordWithChangesImpl(std::optional<evo_test::AliasedRecordWithChanges> const& value) = 0;
  virtual void WriteUnionRecordWithChangesImpl(std::variant<evo_test::RecordWithChanges, int32_t> const& value) = 0;
  virtual void WriteUnionWithSameTypesetImpl(std::variant<float, evo_test::RecordWithChanges, std::string, int32_t> const& value) = 0;
  virtual void WriteUnionWithTypesAddedImpl(std::variant<evo_test::RecordWithChanges, int32_t, float, std::string> const& value) = 0;
  virtual void WriteUnionWithTypesRemovedImpl(std::variant<evo_test::RecordWithChanges, std::string> const& value) = 0;
  virtual void WriteRecordToOptionalImpl(std::optional<evo_test::RecordWithChanges> const& value) = 0;
  virtual void WriteRecordToAliasedOptionalImpl(evo_test::AliasedOptionalRecord const& value) = 0;
  virtual void WriteRecordToUnionImpl(std::variant<evo_test::RecordWithChanges, std::string> const& value) = 0;
  virtual void WriteRecordToAliasedUnionImpl(evo_test::AliasedRecordOrString const& value) = 0;
  virtual void WriteVectorRecordWithChangesImpl(std::vector<evo_test::RecordWithChanges> const& value) = 0;
  virtual void WriteStreamedRecordWithChangesImpl(evo_test::RecordWithChanges const& value) = 0;
  virtual void WriteStreamedRecordWithChangesImpl(std::vector<evo_test::RecordWithChanges> const& value);
  virtual void EndStreamedRecordWithChangesImpl() = 0;
  virtual void CloseImpl() {}

  static std::string schema_;

  static std::vector<std::string> previous_schemas_;

  static std::string SchemaFromVersion(Version version);

  private:
  uint8_t state_ = 0;

  friend class ProtocolWithChangesReaderBase;
};

// Abstract reader for the ProtocolWithChanges protocol.
class ProtocolWithChangesReaderBase {
  public:
  // Ordinal 0.
  void ReadInt8ToInt(int32_t& value);

  // Ordinal 1.
  void ReadInt8ToLong(int64_t& value);

  // Ordinal 2.
  void ReadInt8ToUint(uint32_t& value);

  // Ordinal 3.
  void ReadInt8ToUlong(uint64_t& value);

  // Ordinal 4.
  void ReadInt8ToFloat(float& value);

  // Ordinal 5.
  void ReadInt8ToDouble(double& value);

  // Ordinal 6.
  void ReadIntToUint(uint32_t& value);

  // Ordinal 7.
  void ReadIntToLong(int64_t& value);

  // Ordinal 8.
  void ReadIntToFloat(float& value);

  // Ordinal 9.
  void ReadIntToDouble(double& value);

  // Ordinal 10.
  void ReadUintToUlong(uint64_t& value);

  // Ordinal 11.
  void ReadUintToFloat(float& value);

  // Ordinal 12.
  void ReadUintToDouble(double& value);

  // Ordinal 13.
  void ReadFloatToDouble(double& value);

  // Ordinal 14.
  void ReadIntToString(std::string& value);

  // Ordinal 15.
  void ReadUintToString(std::string& value);

  // Ordinal 16.
  void ReadLongToString(std::string& value);

  // Ordinal 17.
  void ReadUlongToString(std::string& value);

  // Ordinal 18.
  void ReadFloatToString(std::string& value);

  // Ordinal 19.
  void ReadDoubleToString(std::string& value);

  // Ordinal 20.
  void ReadIntToOptional(std::optional<int32_t>& value);

  // Ordinal 21.
  void ReadFloatToOptional(std::optional<float>& value);

  // Ordinal 22.
  void ReadStringToOptional(std::optional<std::string>& value);

  // Ordinal 23.
  void ReadIntToUnion(std::variant<int32_t, bool>& value);

  // Ordinal 24.
  void ReadFloatToUnion(std::variant<float, bool>& value);

  // Ordinal 25.
  void ReadStringToUnion(std::variant<std::string, bool>& value);

  // Ordinal 26.
  void ReadOptionalIntToFloat(std::optional<float>& value);

  // Ordinal 27.
  void ReadOptionalFloatToString(std::optional<std::string>& value);

  // Ordinal 28.
  void ReadAliasedLongToString(evo_test::AliasedLongToString& value);

  // Ordinal 29.
  void ReadStringToAliasedString(evo_test::AliasedString& value);

  // Ordinal 30.
  void ReadStringToAliasedInt(evo_test::AliasedInt& value);

  // Ordinal 31.
  void ReadOptionalIntToUnion(std::variant<std::monostate, int32_t, std::string>& value);

  // Ordinal 32.
  void ReadOptionalRecordToUnion(std::variant<std::monostate, evo_test::RecordWithChanges, std::string>& value);

  // Ordinal 33.
  void ReadRecordWithChanges(evo_test::RecordWithChanges& value);

  // Ordinal 34.
  void ReadAliasedRecordWithChanges(evo_test::AliasedRecordWithChanges& value);

  // Ordinal 35.
  void ReadRecordToRenamedRecord(evo_test::RenamedRecord& value);

  // Ordinal 36.
  void ReadRecordToAliasedRecord(evo_test::AliasedRecordWithChanges& value);

  // Ordinal 37.
  void ReadRecordToAliasedAlias(evo_test::AliasOfAliasedRecordWithChanges& value);

  // Ordinal 38.
  void ReadOptionalRecordWithChanges(std::optional<evo_test::RecordWithChanges>& value);

  // Ordinal 39.
  void ReadAliasedOptionalRecordWithChanges(std::optional<evo_test::AliasedRecordWithChanges>& value);

  // Ordinal 40.
  void ReadUnionRecordWithChanges(std::variant<evo_test::RecordWithChanges, int32_t>& value);

  // Ordinal 41.
  void ReadUnionWithSameTypeset(std::variant<float, evo_test::RecordWithChanges, std::string, int32_t>& value);

  // Ordinal 42.
  void ReadUnionWithTypesAdded(std::variant<evo_test::RecordWithChanges, int32_t, float, std::string>& value);

  // Ordinal 43.
  void ReadUnionWithTypesRemoved(std::variant<evo_test::RecordWithChanges, std::string>& value);

  // Ordinal 44.
  void ReadRecordToOptional(std::optional<evo_test::RecordWithChanges>& value);

  // Ordinal 45.
  void ReadRecordToAliasedOptional(evo_test::AliasedOptionalRecord& value);

  // Ordinal 46.
  void ReadRecordToUnion(std::variant<evo_test::RecordWithChanges, std::string>& value);

  // Ordinal 47.
  void ReadRecordToAliasedUnion(evo_test::AliasedRecordOrString& value);

  // Ordinal 48.
  void ReadVectorRecordWithChanges(std::vector<evo_test::RecordWithChanges>& value);

  // Ordinal 49.
  [[nodiscard]] bool ReadStreamedRecordWithChanges(evo_test::RecordWithChanges& value);

  // Ordinal 49.
  [[nodiscard]] bool ReadStreamedRecordWithChanges(std::vector<evo_test::RecordWithChanges>& values);

  // Optionaly close this writer before destructing. Validates that all steps were completely read.
  void Close();

  void CopyTo(ProtocolWithChangesWriterBase& writer, size_t streamed_record_with_changes_buffer_size = 1);

  virtual ~ProtocolWithChangesReaderBase() = default;

  protected:
  virtual void ReadInt8ToIntImpl(int32_t& value) = 0;
  virtual void ReadInt8ToLongImpl(int64_t& value) = 0;
  virtual void ReadInt8ToUintImpl(uint32_t& value) = 0;
  virtual void ReadInt8ToUlongImpl(uint64_t& value) = 0;
  virtual void ReadInt8ToFloatImpl(float& value) = 0;
  virtual void ReadInt8ToDoubleImpl(double& value) = 0;
  virtual void ReadIntToUintImpl(uint32_t& value) = 0;
  virtual void ReadIntToLongImpl(int64_t& value) = 0;
  virtual void ReadIntToFloatImpl(float& value) = 0;
  virtual void ReadIntToDoubleImpl(double& value) = 0;
  virtual void ReadUintToUlongImpl(uint64_t& value) = 0;
  virtual void ReadUintToFloatImpl(float& value) = 0;
  virtual void ReadUintToDoubleImpl(double& value) = 0;
  virtual void ReadFloatToDoubleImpl(double& value) = 0;
  virtual void ReadIntToStringImpl(std::string& value) = 0;
  virtual void ReadUintToStringImpl(std::string& value) = 0;
  virtual void ReadLongToStringImpl(std::string& value) = 0;
  virtual void ReadUlongToStringImpl(std::string& value) = 0;
  virtual void ReadFloatToStringImpl(std::string& value) = 0;
  virtual void ReadDoubleToStringImpl(std::string& value) = 0;
  virtual void ReadIntToOptionalImpl(std::optional<int32_t>& value) = 0;
  virtual void ReadFloatToOptionalImpl(std::optional<float>& value) = 0;
  virtual void ReadStringToOptionalImpl(std::optional<std::string>& value) = 0;
  virtual void ReadIntToUnionImpl(std::variant<int32_t, bool>& value) = 0;
  virtual void ReadFloatToUnionImpl(std::variant<float, bool>& value) = 0;
  virtual void ReadStringToUnionImpl(std::variant<std::string, bool>& value) = 0;
  virtual void ReadOptionalIntToFloatImpl(std::optional<float>& value) = 0;
  virtual void ReadOptionalFloatToStringImpl(std::optional<std::string>& value) = 0;
  virtual void ReadAliasedLongToStringImpl(evo_test::AliasedLongToString& value) = 0;
  virtual void ReadStringToAliasedStringImpl(evo_test::AliasedString& value) = 0;
  virtual void ReadStringToAliasedIntImpl(evo_test::AliasedInt& value) = 0;
  virtual void ReadOptionalIntToUnionImpl(std::variant<std::monostate, int32_t, std::string>& value) = 0;
  virtual void ReadOptionalRecordToUnionImpl(std::variant<std::monostate, evo_test::RecordWithChanges, std::string>& value) = 0;
  virtual void ReadRecordWithChangesImpl(evo_test::RecordWithChanges& value) = 0;
  virtual void ReadAliasedRecordWithChangesImpl(evo_test::AliasedRecordWithChanges& value) = 0;
  virtual void ReadRecordToRenamedRecordImpl(evo_test::RenamedRecord& value) = 0;
  virtual void ReadRecordToAliasedRecordImpl(evo_test::AliasedRecordWithChanges& value) = 0;
  virtual void ReadRecordToAliasedAliasImpl(evo_test::AliasOfAliasedRecordWithChanges& value) = 0;
  virtual void ReadOptionalRecordWithChangesImpl(std::optional<evo_test::RecordWithChanges>& value) = 0;
  virtual void ReadAliasedOptionalRecordWithChangesImpl(std::optional<evo_test::AliasedRecordWithChanges>& value) = 0;
  virtual void ReadUnionRecordWithChangesImpl(std::variant<evo_test::RecordWithChanges, int32_t>& value) = 0;
  virtual void ReadUnionWithSameTypesetImpl(std::variant<float, evo_test::RecordWithChanges, std::string, int32_t>& value) = 0;
  virtual void ReadUnionWithTypesAddedImpl(std::variant<evo_test::RecordWithChanges, int32_t, float, std::string>& value) = 0;
  virtual void ReadUnionWithTypesRemovedImpl(std::variant<evo_test::RecordWithChanges, std::string>& value) = 0;
  virtual void ReadRecordToOptionalImpl(std::optional<evo_test::RecordWithChanges>& value) = 0;
  virtual void ReadRecordToAliasedOptionalImpl(evo_test::AliasedOptionalRecord& value) = 0;
  virtual void ReadRecordToUnionImpl(std::variant<evo_test::RecordWithChanges, std::string>& value) = 0;
  virtual void ReadRecordToAliasedUnionImpl(evo_test::AliasedRecordOrString& value) = 0;
  virtual void ReadVectorRecordWithChangesImpl(std::vector<evo_test::RecordWithChanges>& value) = 0;
  virtual bool ReadStreamedRecordWithChangesImpl(evo_test::RecordWithChanges& value) = 0;
  virtual bool ReadStreamedRecordWithChangesImpl(std::vector<evo_test::RecordWithChanges>& values);
  virtual void CloseImpl() {}
  static std::string schema_;

  static std::vector<std::string> previous_schemas_;

  static Version VersionFromSchema(const std::string& schema);

  private:
  uint8_t state_ = 0;
};

// Abstract writer for the UnusedProtocol protocol.
class UnusedProtocolWriterBase {
  public:
  // Ordinal 0.
  // Call this method for each element of the `samples` stream, then call `EndSamples() when done.`
  void WriteSamples(evo_test::UnchangedRecord const& value);

  // Ordinal 0.
  // Call this method to write many values to the `samples` stream, then call `EndSamples()` when done.
  void WriteSamples(std::vector<evo_test::UnchangedRecord> const& values);

  // Marks the end of the `samples` stream.
  void EndSamples();

  // Optionaly close this writer before destructing. Validates that all steps were completed.
  void Close();

  virtual ~UnusedProtocolWriterBase() = default;

  // Flushes all buffered data.
  virtual void Flush() {}

  protected:
  virtual void WriteSamplesImpl(evo_test::UnchangedRecord const& value) = 0;
  virtual void WriteSamplesImpl(std::vector<evo_test::UnchangedRecord> const& value);
  virtual void EndSamplesImpl() = 0;
  virtual void CloseImpl() {}

  static std::string schema_;

  static std::vector<std::string> previous_schemas_;

  static std::string SchemaFromVersion(Version version);

  private:
  uint8_t state_ = 0;

  friend class UnusedProtocolReaderBase;
};

// Abstract reader for the UnusedProtocol protocol.
class UnusedProtocolReaderBase {
  public:
  // Ordinal 0.
  [[nodiscard]] bool ReadSamples(evo_test::UnchangedRecord& value);

  // Ordinal 0.
  [[nodiscard]] bool ReadSamples(std::vector<evo_test::UnchangedRecord>& values);

  // Optionaly close this writer before destructing. Validates that all steps were completely read.
  void Close();

  void CopyTo(UnusedProtocolWriterBase& writer, size_t samples_buffer_size = 1);

  virtual ~UnusedProtocolReaderBase() = default;

  protected:
  virtual bool ReadSamplesImpl(evo_test::UnchangedRecord& value) = 0;
  virtual bool ReadSamplesImpl(std::vector<evo_test::UnchangedRecord>& values);
  virtual void CloseImpl() {}
  static std::string schema_;

  static std::vector<std::string> previous_schemas_;

  static Version VersionFromSchema(const std::string& schema);

  private:
  uint8_t state_ = 0;
};
} // namespace evo_test
