// This file was generated by the "yardl" tool. DO NOT EDIT.

#pragma once
#include <array>
#include <complex>
#include <optional>
#include <unordered_map>
#include <variant>
#include <vector>

#include "yardl/yardl.h"

namespace evo_test {
using AliasedLongToString = std::string;

struct UnchangedRecord {
  std::string name{};
  int32_t age{};
  std::unordered_map<std::string, double> meta{};

  bool operator==(const UnchangedRecord& other) const {
    return name == other.name &&
      age == other.age &&
      meta == other.meta;
  }

  bool operator!=(const UnchangedRecord& other) const {
    return !(*this == other);
  }
};

struct RecordWithChanges {
  double float_to_double{};
  evo_test::UnchangedRecord unchanged_record{};
  int64_t int_to_long{};
  std::optional<std::string> optional_long_to_string{};

  bool operator==(const RecordWithChanges& other) const {
    return float_to_double == other.float_to_double &&
      unchanged_record == other.unchanged_record &&
      int_to_long == other.int_to_long &&
      optional_long_to_string == other.optional_long_to_string;
  }

  bool operator!=(const RecordWithChanges& other) const {
    return !(*this == other);
  }
};

using AliasedRecordWithChanges = evo_test::RecordWithChanges;

} // namespace evo_test

