# This file was generated by the "yardl" tool. DO NOT EDIT.


import dataclasses
import datetime
import enum
import typing
import numpy as np
import numpy.typing as npt
from . import yardl_types as yardl

class MyFlags(enum.Flag):
    """This is my enum"""
    A = 1
    """This is the "A" value"""
    B = 2
    C = 4

@dataclasses.dataclass(slots=True, kw_only=True)
class Point:
    """MyRec<T>: !record
      fields:
        f1: int?
        f2: T
        f3: MyFlags

    # This is a string
    MyString: string

    R2<T>: !record
      fields:
        r2: MyRec<T>

    R: MyRec<string>

    MyInt: [int, float]
    """
    x: yardl.Int32
    y: yardl.Int32

