version: '3'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  matlab:
    image: mathworks/matlab:r2023b
    volumes:
      - ../..:/workspaces:cached
    environment:
      - MLM_LICENSE_FILE={{ matlab_license_server }}
    entrypoint: /bin/bash
    network_mode: service:devcontainer
    init: true
    tty: true
