name: smoketest

on:
  push:
    # branches: [main]
    # tags: ["v*.*.*"]
  pull_request:

defaults:
  run:
    # See https://github.com/marketplace/actions/setup-miniconda#important
    shell: bash -el {0}

jobs:
  buildBinaries:
    name: Build yardl binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3' # The Go version to download (if necessary) and use.

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: v1.13.0
          args: release --rm-dist --snapshot

      - name: Upload yardl binaries
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  smoketestWindows:
    name: Run smoketest on Windows
    runs-on: windows-latest
    needs: buildBinaries
    steps:
      - uses: actions/checkout@v3

      - name: Download yardl binaries
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Set path
        shell: pwsh
        run: Add-Content $env:GITHUB_PATH "${{github.workspace}}\yardl_windows_amd64_v1"

      - name: yardl init
        shell: pwsh
        run: |
          mkdir smoketest\model
          cd smoketest\model
          yardl init smoketest
          yardl generate

      - name: build smoketest
        shell: pwsh
        run: |
          mkdir smoketest\cpp\build
          cd smoketest\cpp\build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
          cmake --build .

      - name: Run smoketest
        shell: pwsh
        run: smoketest\cpp\build\Debug\smoketest.exe
